source 'https://rubygems.org'

ruby '3.2.0'

# Core gems
gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'sinatra-cross_origin', '~> 0.4'

# Database
gem 'pg', '~> 1.5'
gem 'activerecord', '~> 7.0'
gem 'sinatra-activerecord', '~> 2.0'

# JSON handling
gem 'json', '~> 2.6'
gem 'rack-json', '~> 0.1'

# Authentication & Security
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.7'

# Validation
gem 'activemodel', '~> 7.0'

# Development gems
group :development do
  gem 'pry', '~> 0.14'
  gem 'pry-byebug', '~> 3.10'
  gem 'dotenv', '~> 2.8'
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
end 